
# Auto Generated File
# Do not edit this file.

MANIFEST_VERSION = 1314469494.86

MANIFEST = """
CACHE MANIFEST
# version 27 - Aug - Y 1314469494.86

# Explicitly cached 'master entries'.
CACHE:
build/bin.albumspage.js
build/bin.basepage.js
build/bin.dockpage.js
build/bin.friendspage.js
build/bin.groupspage.js
build/bin.homepage.js
build/bin.photopage.js
build/bin.photospage.js
build/bin.profilepage.js
build/bin.startup.js
build/bin.tbdpage.js
build/bin.all.css
build/bin.all.embed.css
build/min.all.css

# Resources that require the user to be online.
NETWORK:
*
"""
