
# Auto Generated File
# Do not edit this file.

MANIFEST_VERSION = 1314730053.6

MANIFEST = """
CACHE MANIFEST
# version 30 - Aug - Y 1314730053.6

# Explicitly cached 'master entries'.
CACHE:
http://connect.facebook.net/en_US/all.js
https://connect.facebook.net/en_US/all.js
build/bin.albumspage.js
build/bin.basepage.js
build/bin.dockpage.js
build/bin.friendspage.js
build/bin.groupspage.js
build/bin.homepage.js
build/bin.photopage.js
build/bin.photospage.js
build/bin.placespage.js
build/bin.profilepage.js
build/bin.startup.js
build/bin.tbdpage.js
build/bin.all.css
build/bin.all.embed.css
build/min.all.css

# Resources that require the user to be online.
NETWORK:
*

FALLBACK:
/ /offline

"""
